### ISSUE TITLE
PyTorch version compatibility

### ISSUE THREAD

**Issue by ni-wei** [shashiongithub/XSum#10]
Hi,

firstly, thanks very much for the great work.

The issue I raise here is about the PyTorch version that makes XSum work. When I installed my PyTorch in my conda environment using "pip install torch", it installed the latest torch 1.0.1.post2. This specific torch version seemed to cause an AttributeError, which I believe is a compatibility issue. In contrast, torch 0.4.0 or 0.4.1 works, and no compatibility issue exists. 

Therefore, does ["Our code requires PyTorch version >= 0.4.0"](https://github.com/EdinburghNLP/XSum#installation) actually mean PyTorch version 0.4.0 or 0.4.1?

**Comment by shashiongithub** [comment]
Thanks for your valuable comment. I will update the page.
