### ISSUE TITLE
noise in the dataset

### ISSUE THREAD

**Issue by dykang** [shashiongithub/XSum#14]
Thanks for the wonderful repo! I have a question in the data collection part. 

I exactly followed the instructions and found that there are many noisy texts in the dataset such as "Share this with email facebook messenger ..... copy this link" in the had of many documents. 

Did you train your model on the dataset with these noises? Are those numbers in the paper with the noisy text? Or, please let me know if I am wrong. I just need clarification so we can filter them out for valid replication. 

Thank you again for your amazing work!

**Comment by shashiongithub** [comment]
It is possible that some of them were there with the articles. All texts with <p></p> within main body were kept.
