### ISSUE TITLE
Raw dataset

### ISSUE THREAD

**Issue by astariul** [shashiongithub/XSum#20]
I saw the dataset is available at http://kinloch.inf.ed.ac.uk/public/direct/XSUM-EMNLP18-Summary-Data-Original.tar.gz (link given by @shashiongithub )

I tried to use this dataset to reproduce BART results, but I couldn't. According to one of BART author on [this issue (fairseq repository)](https://github.com/pytorch/fairseq/issues/1971#issuecomment-610145639), this is because I'm using an already processed version of the dataset.

---

**Is it possible to have a link to the raw dataset (no postprocess of any kind) ?**

**Comment by wonjininfo** [comment]
Same here. 
I tried to download raw data using the script but faced an error (same for issue #12)
Since I use BART, I would appreciate it if I can access the raw dataset.

**Comment by shashiongithub** [comment]
Yes, there has been some issue with downloading the raw data using the script. Some of the wayback urls have expired. 

The dataset at the url mentioned at the top of this post is the same that was used in our paper and also shared with BART authors. Please only use entries that are provided here: https://github.com/EdinburghNLP/XSum/blob/master/XSum-Dataset/XSum-TRAINING-DEV-TEST-SPLIT-90-5-5.json

**Comment by addf400** [comment]
@shashiongithub @Colanim 

When I tried to get the XSUM dataset from url you shared (http://kinloch.inf.ed.ac.uk/public/direct/XSUM-EMNLP18-Summary-Data-Original.tar.gz), I encountered the following error:
You don't have permission to access /public/direct/XSUM-EMNLP18-Summary-Data-Original.tar.gz on this server.

Can you help me to access the raw dataset? 
Many thanks!

**Comment by shashiongithub** [comment]
Try replacing kinloch with bollin.

**Comment by addf400** [comment]
> Try replacing kinloch with bollin.

It works !
