### ISSUE TITLE
Bad Output

### ISSUE THREAD

**Issue by matt9704** [shashiongithub/XSum#25]
Hi! I completely follow the instruction for ConvS2S model, i.e. data preprocessing, model training , generation and extract final hypothesis. I'm wondering why the output file is in .pt format (final-test-output-convs2s-checkpoint-best.pt)?? 
Isn't it supposed to be a .txt file because it contains generated summaries???
And, when I open the generated final-test-output-convs2s-checkpoint-best.pt file, it looks like:
![image](https://user-images.githubusercontent.com/62277482/87426960-f5298180-c5d7-11ea-8500-808bab76c3a6.png)

**Comment by ghost** [comment]
Hi, I have encountered the same problem. Have you fixed it? Could you please help me or give me some advice?
My email address is ramon.zhan@outlook.com
Thanks, A LOT!!!

**Comment by SumanthSrungavarapu** [comment]
hey have you solved this?
