### ISSUE TITLE
Error in downloading data

### ISSUE THREAD

**Issue by jiacheng-xu** [shashiongithub/XSum#4]
~/XSum/XSum-Dataset$ python scripts/download-bbc-articles.py
Creating the download directory.
Downloading URLs from the XSum-WebArxiveUrls.txt file:
urls left to download: 226711
5.19% [11765/226711]Traceback (most recent call last):
  File "scripts/download-bbc-articles.py", line 253, in <module>
    main()
  File "scripts/download-bbc-articles.py", line 248, in main
    DownloadMode(urls_file_to_download, missing_urls_file, downloads_dir, args.request_parallelism, args.timestamp_exactness)
  File "scripts/download-bbc-articles.py", line 198, in DownloadMode
    for url, story_html in results:
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

I know probably I can fix this issue but I want to make sure the copy of the dataset is exactly the same as you use in the paper. Could you just upload the dataset to Dropbox or Google cloud? or fix this issue. thx.

**Comment by shashiongithub** [comment]
hi, 
We are not sure about the rights for releasing the whole BBC dataset. We are looking into that. 
For the moment, I have added that exception to the script. 
To avoid too many redirects, try using "timestamp_exactness". 

"[Sep 19, 2018]: Each URL includes a timestamp (14 letters; year, month, date, hour, minute and second, e.g., 20130206080312) showing when it was stored. By default, it is set to 14 letters. You can lower this to improve your chances to download a BBC article. For example, with timestamp_exactness=4 the time stamp will be chopped to first 4 letters (i.e., 2013) and it will try to download a version of the article stored in 2013 (any month, date, hour, minute or second). Every time you rerun the download script, lower the timestamp_exactness (>= 1) to improve the chances of getting missed URLs from the previous step. However, lower the timestamp_exactness value, more time it will take to retrieve the article."

**Comment by jiacheng-xu** [comment]
thank you so much.

**Comment by jiacheng-xu** [comment]
Hi,
I tried to download the data. It almost works out but there are 53 URLs not available. Do you have any idea how to fix this part of the dataset? Some of them expire I suppose.

List here:
http://web.archive.org/web/20120527084827/http://www.bbc.co.uk/newsround/14419663
http://web.archive.org/web/20170221171941/http://www.bbc.co.uk/sport/olympics/18908843
http://web.archive.org/web/20141228032248/http://www.bbc.co.uk/sport/cricket/30612377
http://web.archive.org/web/20170415153042/http://www.bbc.co.uk/sport/olympics/18909585
http://web.archive.org/web/20110910174956/http://www.bbc.co.uk/news/uk-wales-14850225
http://web.archive.org/web/20170205213800/http://www.bbc.co.uk/sport/olympics/18904467
http://web.archive.org/web/20141226153103/http://www.bbc.co.uk/sport/cricket/30605007
http://web.archive.org/web/20170620203918/http://www.bbc.com/sport/olympics/18914952
http://web.archive.org/web/20170110145026/http://www.bbc.co.uk/news/uk-scotland-35375292
http://web.archive.org/web/20170607140959/http://www.bbc.com/news/world-europe-40185222
http://web.archive.org/web/20160626113836/http://www.bbc.co.uk/news/uk-wales-36559141
http://web.archive.org/web/20141001040001/http://www.bbc.co.uk/news/uk-politics-18759639
http://web.archive.org/web/20141123152845/http://www.bbc.co.uk/sport/tennis/30167687
http://web.archive.org/web/20141218161609/http://www.bbc.co.uk/sport/darts/30025020
http://web.archive.org/web/20170301214218/http://www.bbc.co.uk/sport/olympics/18912097
http://web.archive.org/web/20170223221410/http://www.bbc.co.uk/news/uk-northern-ireland-politics-39070619
http://web.archive.org/web/20170211095710/http://www.bbc.co.uk:80/news/technology-35600617
http://web.archive.org/web/20151229175507/http://www.bbc.co.uk/sport/football/35185636/
http://web.archive.org/web/20170107172027/http://www.bbc.co.uk:80/news/technology-35400377
http://web.archive.org/web/20141223180801/http://www.bbc.co.uk/sport/athletics/30585334
http://web.archive.org/web/20141223055543/http://www.bbc.co.uk/sport/formula-one/30580526
http://web.archive.org/web/20170101053113/http://www.bbc.co.uk/news/business-35388127
http://web.archive.org/web/20151205133341/http://www.bbc.co.uk/sport/football/34975551
http://web.archive.org/web/20170714202129/http://www.bbc.co.uk/sport/football/28360657
http://web.archive.org/web/20161004081827/http://www.bbc.co.uk/sport/golf/29404756
http://web.archive.org/web/20170406092005/http://www.bbc.co.uk/sport/olympics/18903411
http://web.archive.org/web/20170821205035/http://www.bbc.co.uk/news/world-us-canada-40941341
http://web.archive.org/web/20160413092312/http://www.bbc.co.uk/sport/football/36000151
http://web.archive.org/web/20110914105252/http://www.bbc.co.uk/news/uk-northern-ireland-14850720
http://web.archive.org/web/20170304014210/http://www.bbc.co.uk/news/entertainment-arts-37487365
http://web.archive.org/web/20170331122550/http://www.bbc.co.uk/news/uk-wales-south-east-wales-39454623
http://web.archive.org/web/20160326180957/http://www.bbc.co.uk/news/uk-england-london-35901508
http://web.archive.org/web/20170204081520/http://www.bbc.co.uk:80/sport/olympics/18916209
http://web.archive.org/web/20150408234224/http://www.bbc.co.uk/news/uk-wales-mid-wales-32221065
http://web.archive.org/web/20110910174928/http://www.bbc.co.uk/news/uk-northern-ireland-14856231
http://web.archive.org/web/20141229215715/http://www.bbc.co.uk/sport/football/30628138
http://web.archive.org/web/20100910234738/http://www.bbc.co.uk/newsbeat/10001244
http://web.archive.org/web/20170421000247/http://www.bbc.co.uk/news/technology-39661299
http://web.archive.org/web/20170521054906/http://www.bbc.co.uk/sport/modern-pentathlon/16492991
http://web.archive.org/web/20160505100015/http://www.bbc.co.uk/sport/football/24879138
http://web.archive.org/web/20150701231054/http://www.bbc.co.uk/news/uk-england-tees-33348238
http://web.archive.org/web/20170307072322/http://www.bbc.co.uk/sport/0/football/34928364
http://web.archive.org/web/20141217092853/http://www.bbc.co.uk/sport/formula1/30501655
http://web.archive.org/web/20170112142929/http://www.bbc.co.uk:80/sport/football/38419024
http://web.archive.org/web/20110910164811/http://www.bbc.co.uk/news/uk-wales-14806530
http://web.archive.org/web/20170226095055/http://www.bbc.co.uk:80/news/technology-35362325
http://web.archive.org/web/20170115195250/http://www.bbc.co.uk/sport/olympics/18915973
http://web.archive.org/web/20170408021424/http://www.bbc.com/sport/olympics/18912148
http://web.archive.org/web/20170101022244/http://www.bbc.co.uk/sport/olympics/18912882
http://web.archive.org/web/20170203011914/http://www.bbc.co.uk/sport/olympics/18903420
http://web.archive.org/web/20170420012658/http://www.bbc.co.uk/news/uk-wales-south-east-wales-39292621
http://web.archive.org/web/20151124154557/http://www.bbc.co.uk/sport/football/34913514
http://web.archive.org/web/20170203011914/http://www.bbc.co.uk/sport/olympics/18911820

**Comment by shashiongithub** [comment]
I sent you an email with those missing files.

**Comment by jiacheng-xu** [comment]
thank you.

**Comment by marythomaa98** [comment]
Hi , 
I am having same issue, unable to download the following urls:
http://web.archive.org/web/20170301232318/http://www.bbc.co.uk/news/science-environment-33731391
http://web.archive.org/web/20150622093819/http://www.bbc.co.uk/news/world-asia-33197683
http://web.archive.org/web/20110910174956/http://www.bbc.co.uk/news/uk-wales-14850225
http://web.archive.org/web/20161004073744/http://www.bbc.co.uk/news/uk-scotland-34060154
http://web.archive.org/web/20170125222538/http://www.bbc.co.uk/sport/football/35902167
http://web.archive.org/web/20160328112806/http://www.bbc.co.uk/news/uk-scotland-edinburgh-east-fife-35910638
http://web.archive.org/web/20170113133649/http://www.bbc.co.uk:80/news/science-environment-34192372
http://web.archive.org/web/20170113181911/http://www.bbc.co.uk/news/uk-politics-37300254
http://web.archive.org/web/20151114095946/http://www.bbc.co.uk/news/business-34795045
http://web.archive.org/web/20170127134958/http://www.bbc.com/news/uk-wales-38762156
http://web.archive.org/web/20110914105252/http://www.bbc.co.uk/news/uk-northern-ireland-14850720
http://web.archive.org/web/20170107163811/http://www.bbc.co.uk/news/uk-england-kent-38081845
http://web.archive.org/web/20170324002444/http://www.bbc.co.uk/sport/rugby-union/39366908
http://web.archive.org/web/20170211150318/http://www.bbc.co.uk/sport/football/38143657
http://web.archive.org/web/20110910164811/http://www.bbc.co.uk/news/uk-wales-14806530
http://web.archive.org/web/20150613044301/http://www.bbc.co.uk/news/uk-politics-33082125
http://web.archive.org/web/20170506184653/http://www.bbc.com/news/uk-england-oxfordshire-38376684
http://web.archive.org/web/20170714180651/http://www.bbc.co.uk/news/uk-scotland-highlands-islands-40597885
http://web.archive.org/web/20170208123034/http://www.bbc.co.uk:80/sport/football/38885621
http://web.archive.org/web/20160619055513/http://www.bbc.co.uk/news/science-environment-34275758
http://web.archive.org/web/20170419014546/http://www.bbc.co.uk/news/uk-scotland-34051104
http://web.archive.org/web/20120527084827/http://www.bbc.co.uk/newsround/14419663
http://web.archive.org/web/20151231194343/http://www.bbc.co.uk/news/uk-wales-35201832
http://web.archive.org/web/20170213005542/http://www.bbc.co.uk/news/science-environment-34771511
http://web.archive.org/web/20160421131709/http://www.bbc.co.uk/news/uk-england-cumbria-36026802
http://web.archive.org/web/20160519200623/http://www.bbc.co.uk/news/uk-scotland-tayside-central-36323895
http://web.archive.org/web/20160227215811/http://www.bbc.co.uk/sport/rugby-union/35678174
http://web.archive.org/web/20170714202129/http://www.bbc.co.uk/sport/football/28360657
http://web.archive.org/web/20150601153222/http://www.bbc.co.uk/news/uk-england-stoke-staffordshire-32903337
http://web.archive.org/web/20170207042503/http://www.bbc.co.uk/news/uk-35633673
http://web.archive.org/web/20170725004016/http://www.bbc.co.uk/sport/football/28169062
http://web.archive.org/web/20170207031543/http://www.bbc.com/news/uk-england-london-37717676
http://web.archive.org/web/20170328091005/http://www.bbc.co.uk/news/science-environment-33612294
http://web.archive.org/web/20170211052648/http://www.bbc.co.uk:80/news/science-environment-34191713
http://web.archive.org/web/20170715035543/http://www.bbc.com/news/uk-scotland-south-scotland-40592884
http://web.archive.org/web/20160924233640/http://www.bbc.co.uk/news/science-environment-33531811
http://web.archive.org/web/20170509012046/http://www.bbc.co.uk/news/uk-england-39849272
http://web.archive.org/web/20160730160534/http://www.bbc.co.uk/news/science-environment-33206661
http://web.archive.org/web/20170415022507/http://www.bbc.co.uk/news/uk-england-bristol-39566150
http://web.archive.org/web/20170302142437/http://www.bbc.co.uk/news/uk-scotland-south-scotland-37186373
http://web.archive.org/web/20160311215959/http://www.bbc.co.uk/news/world-latin-america-35788012/
http://web.archive.org/web/20170531121646/http://www.bbc.co.uk/sport/cricket/40079895
http://web.archive.org/web/20170107192123/http://www.bbc.co.uk/news/technology-26578264
http://web.archive.org/web/20110910174928/http://www.bbc.co.uk/news/uk-northern-ireland-14856231
http://web.archive.org/web/20150116065758/http://www.bbc.co.uk/news/world-africa-30818642
http://web.archive.org/web/20170620203918/http://www.bbc.com/sport/olympics/18914952
http://web.archive.org/web/20160307172305/http://www.bbc.co.uk/news/world-latin-america-35744130
http://web.archive.org/web/20100910234738/http://www.bbc.co.uk/newsbeat/10001244
http://web.archive.org/web/20160830112004/http://www.bbc.co.uk/news/uk-scotland-south-scotland-37194266
http://web.archive.org/web/20170512193825/http://www.bbc.com/news/uk-politics-uk-leaves-the-eu-36839610
http://web.archive.org/web/20150715010519/http://www.bbc.com/news/uk-politics-33496575
http://web.archive.org/web/20141001040001/http://www.bbc.co.uk/news/uk-politics-18759639
http://web.archive.org/web/20170109063516/http://www.bbc.co.uk/news/uk-scotland-34060155
http://web.archive.org/web/20160826084342/http://www.bbc.com/news/uk-politics-uk-leaves-the-eu-36844932
http://web.archive.org/web/20150609111259/http://www.bbc.co.uk/sport/football/33050252
http://web.archive.org/web/20170531044502/http://www.bbc.co.uk/news/uk-scotland-scotland-politics-40100178
http://web.archive.org/web/20170219112517/http://www.bbc.co.uk:80/sport/football/37388622
http://web.archive.org/web/20170831175534/http://www.bbc.co.uk/news/world-asia-china-30808665
http://web.archive.org/web/20170620171909/http://www.bbc.co.uk/news/world-us-canada-36670145
http://web.archive.org/web/20160209174746/http://www.bbc.co.uk/news/world-us-canada-35534633

**Comment by marythomaa98** [comment]
> Hi ,
> I am having same issue, unable to download the following urls:
> http://web.archive.org/web/20170301232318/http://www.bbc.co.uk/news/science-environment-33731391
> http://web.archive.org/web/20150622093819/http://www.bbc.co.uk/news/world-asia-33197683
> http://web.archive.org/web/20110910174956/http://www.bbc.co.uk/news/uk-wales-14850225
> http://web.archive.org/web/20161004073744/http://www.bbc.co.uk/news/uk-scotland-34060154
> http://web.archive.org/web/20170125222538/http://www.bbc.co.uk/sport/football/35902167
> http://web.archive.org/web/20160328112806/http://www.bbc.co.uk/news/uk-scotland-edinburgh-east-fife-35910638
> http://web.archive.org/web/20170113133649/http://www.bbc.co.uk:80/news/science-environment-34192372
> http://web.archive.org/web/20170113181911/http://www.bbc.co.uk/news/uk-politics-37300254
> http://web.archive.org/web/20151114095946/http://www.bbc.co.uk/news/business-34795045
> http://web.archive.org/web/20170127134958/http://www.bbc.com/news/uk-wales-38762156
> http://web.archive.org/web/20110914105252/http://www.bbc.co.uk/news/uk-northern-ireland-14850720
> http://web.archive.org/web/20170107163811/http://www.bbc.co.uk/news/uk-england-kent-38081845
> http://web.archive.org/web/20170324002444/http://www.bbc.co.uk/sport/rugby-union/39366908
> http://web.archive.org/web/20170211150318/http://www.bbc.co.uk/sport/football/38143657
> http://web.archive.org/web/20110910164811/http://www.bbc.co.uk/news/uk-wales-14806530
> http://web.archive.org/web/20150613044301/http://www.bbc.co.uk/news/uk-politics-33082125
> http://web.archive.org/web/20170506184653/http://www.bbc.com/news/uk-england-oxfordshire-38376684
> http://web.archive.org/web/20170714180651/http://www.bbc.co.uk/news/uk-scotland-highlands-islands-40597885
> http://web.archive.org/web/20170208123034/http://www.bbc.co.uk:80/sport/football/38885621
> http://web.archive.org/web/20160619055513/http://www.bbc.co.uk/news/science-environment-34275758
> http://web.archive.org/web/20170419014546/http://www.bbc.co.uk/news/uk-scotland-34051104
> http://web.archive.org/web/20120527084827/http://www.bbc.co.uk/newsround/14419663
> http://web.archive.org/web/20151231194343/http://www.bbc.co.uk/news/uk-wales-35201832
> http://web.archive.org/web/20170213005542/http://www.bbc.co.uk/news/science-environment-34771511
> http://web.archive.org/web/20160421131709/http://www.bbc.co.uk/news/uk-england-cumbria-36026802
> http://web.archive.org/web/20160519200623/http://www.bbc.co.uk/news/uk-scotland-tayside-central-36323895
> http://web.archive.org/web/20160227215811/http://www.bbc.co.uk/sport/rugby-union/35678174
> http://web.archive.org/web/20170714202129/http://www.bbc.co.uk/sport/football/28360657
> http://web.archive.org/web/20150601153222/http://www.bbc.co.uk/news/uk-england-stoke-staffordshire-32903337
> http://web.archive.org/web/20170207042503/http://www.bbc.co.uk/news/uk-35633673
> http://web.archive.org/web/20170725004016/http://www.bbc.co.uk/sport/football/28169062
> http://web.archive.org/web/20170207031543/http://www.bbc.com/news/uk-england-london-37717676
> http://web.archive.org/web/20170328091005/http://www.bbc.co.uk/news/science-environment-33612294
> http://web.archive.org/web/20170211052648/http://www.bbc.co.uk:80/news/science-environment-34191713
> http://web.archive.org/web/20170715035543/http://www.bbc.com/news/uk-scotland-south-scotland-40592884
> http://web.archive.org/web/20160924233640/http://www.bbc.co.uk/news/science-environment-33531811
> http://web.archive.org/web/20170509012046/http://www.bbc.co.uk/news/uk-england-39849272
> http://web.archive.org/web/20160730160534/http://www.bbc.co.uk/news/science-environment-33206661
> http://web.archive.org/web/20170415022507/http://www.bbc.co.uk/news/uk-england-bristol-39566150
> http://web.archive.org/web/20170302142437/http://www.bbc.co.uk/news/uk-scotland-south-scotland-37186373
> http://web.archive.org/web/20160311215959/http://www.bbc.co.uk/news/world-latin-america-35788012/
> http://web.archive.org/web/20170531121646/http://www.bbc.co.uk/sport/cricket/40079895
> http://web.archive.org/web/20170107192123/http://www.bbc.co.uk/news/technology-26578264
> http://web.archive.org/web/20110910174928/http://www.bbc.co.uk/news/uk-northern-ireland-14856231
> http://web.archive.org/web/20150116065758/http://www.bbc.co.uk/news/world-africa-30818642
> http://web.archive.org/web/20170620203918/http://www.bbc.com/sport/olympics/18914952
> http://web.archive.org/web/20160307172305/http://www.bbc.co.uk/news/world-latin-america-35744130
> http://web.archive.org/web/20100910234738/http://www.bbc.co.uk/newsbeat/10001244
> http://web.archive.org/web/20160830112004/http://www.bbc.co.uk/news/uk-scotland-south-scotland-37194266
> http://web.archive.org/web/20170512193825/http://www.bbc.com/news/uk-politics-uk-leaves-the-eu-36839610
> http://web.archive.org/web/20150715010519/http://www.bbc.com/news/uk-politics-33496575
> http://web.archive.org/web/20141001040001/http://www.bbc.co.uk/news/uk-politics-18759639
> http://web.archive.org/web/20170109063516/http://www.bbc.co.uk/news/uk-scotland-34060155
> http://web.archive.org/web/20160826084342/http://www.bbc.com/news/uk-politics-uk-leaves-the-eu-36844932
> http://web.archive.org/web/20150609111259/http://www.bbc.co.uk/sport/football/33050252
> http://web.archive.org/web/20170531044502/http://www.bbc.co.uk/news/uk-scotland-scotland-politics-40100178
> http://web.archive.org/web/20170219112517/http://www.bbc.co.uk:80/sport/football/37388622
> http://web.archive.org/web/20170831175534/http://www.bbc.co.uk/news/world-asia-china-30808665
> http://web.archive.org/web/20170620171909/http://www.bbc.co.uk/news/world-us-canada-36670145
> http://web.archive.org/web/20160209174746/http://www.bbc.co.uk/news/world-us-canada-35534633

can you please sent these files to this email : thomasmary31@gmail.com
