### ISSUE TITLE
How to train a new model using my data

### ISSUE THREAD

**Issue by jawdat23** [shashiongithub/XSum#6]
Thank you very much for this great job,
I just need to ask you how can I train a new model on a new data-set.
I just want to know what is the from the data should be so the model can be trained on them.
thanks in advanced.

**Comment by shashiongithub** [comment]
Setup is same as in Machine translation:
1) a document file: each line is  a document as a sequence of tokens. 
2) Paired summariy file: each line a summary as a sequence of tokens.
